header:
  license:
    content: "SPDX-License-Identifier: GPL-3.0-or-later"
  paths:
    - '**/*.go'
  paths-ignore:
    - '**/*.md'
    - '**/.git/**'
    - 'docs/docs.go'
  comment: on-failure
  license-location-threshold: 10
