openapi: 3.1.0
info:
  title: Scribe-Server API
  version: 0.0.0
paths:
  /latest:
    get:
      operationId: latest
      responses:
        "200":
          description: Returns the datetime of the latest Scribe data update.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LatestUpdateTime"
        "500":
          description: Internal server error occurred.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /language:
    get:
      operationId: list
      responses:
        "200":
          description: Returns the list of languages with available Scribe data.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Language"
        "500":
          description: Internal server error occurred.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /language/{code}:
    get:
      operationId: get
      parameters:
        - name: code
          in: path
          description: Language code of the language.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Language was found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Language"
        "400":
          description: Bad parameters passed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Language was not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error occurred.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
    LatestUpdateTime:
      type: object
      properties:
        updateTime:
          type: string
    Language:
      type: object
      properties:
        code:
          type: string
        name:
          type: string
        wikidataId:
          type: string
