name: CI
on:
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Install dependencies
        run: go get .
        
      - name: Test with the Go 
        run: make test

      - name: Build
        run: make build 